### ISSUE TITLE
LookupAsync() differences on IMobileServiceTable vs. IMobileServiceSyncTable

### ISSUE THREAD

**Issue by gc435** [Azure/azure-mobile-apps-net-client#103]
If a `LookupAsync()` on an `IMobileServiceSyncTable<T>` finds no results, it returns `null`.  If `LookupAsync()` finds no results in an `IMobileServiceTable<T>`, it instead throws a `MobileServiceInvalidOperationException`.

Is it by design that `LookupAsync()` behaves differently in these two cases?  I think it's preferable that it returns null in either event.

**Comment by elamalani** [comment]
@gc435 Thanks for using Azure Mobile Apps. Since this issue is almost 2 years old, I'll close it for now but feel free to ask us questions if you have any. Also, please refer to the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps).
