### ISSUE TITLE
Offline sync: transaction support

### ISSUE THREAD

**Issue by ltaljaard** [Azure/azure-mobile-apps-net-client#116]
Whenever one needs to save changes to local tables atomically it's a problem because there is currently no support for transactions on the client side/local device.

I view this as a critical feature for any serious data driven app, to ensure data consistency.

One can only do so much with a custom solution to achieve this, e.g. if the second in a set of three supposed-to-be-atomic local DB updates throws an exception it would be very tricky to try and manually reverse the first DB update. This is exacerbated by the added complexity of the Azure Mobile Sync framework's tracking of changes to the local db (tables __operations and __errors etc).

**Comment by shrishrirang** [comment]
@ltaljaard Thanks for your feedback. Adding support for transactions has been on our backlog. Adding support for transactions in the local store / database is relatively easy, but the trickier part has been preserving the transaction semantics while sending the changes to the server and while pulling changes from the server and without having to enable change tracking in the database.

**Comment by ltaljaard** [comment]
@shrishrirang thanks, what is the timeframe that you are looking at to get this working? And in the mean time is there anything that I can do to get the client-side transactions working at least?

**Comment by lindydonna** [comment]
@ltaljaard We don't have a timeframe to share, but it's a really big design change to our offline sync implementation. We'll update with a milestone once the work is actually scheduled.

**Comment by adrianhall** [comment]
Closing this off.

This library will NOT be getting transaction support.

It is possible that we will produce a faintly compatible set of client/server libraries in the future that can do transactions, but it won't be THIS library.  The reason is fairly rudimentary to the protocol.  Without protocol support for transactions, we won't be able to do this.  If we change the protocol, then we have to re-implement both server and client.  That will be a part of a future library.
