### ISSUE TITLE
MobileServiceClient.LoginAsync to custom provider results in GET request

### ISSUE THREAD

**Issue by nhwilly** [Azure/azure-mobile-apps-net-client#149]
Using the quick start from Azure Mobile Apps and trying to call a custom controller for authentication.

If I use the signature 
`TodoItemManager.DefaultManager.CurrentClient.LoginAsync(this,   "CustomAuth", authUserDictionary );`
I get a response of:
`<Error>
    <Message>
        The requested resource does not support http method 'GET'.
    </Message>
</Error>`

If I call it with 
`var customUser = await TodoItemManager.DefaultManager.CurrentClient.LoginAsync(this, "CustomAuth");`
I get the same thing.

But if I call it with 
`var customUser = await TodoItemManager.DefaultManager.CurrentClient.LoginAsync("CustomAuth", jauth);`

It works just fine as a POST request as outlined in the documentation.

I am really wanting to just call the method with the context and the controller name (middle option above).  

Am I not doing this right?

Very happy with the new additions to the library, btw.  Looks like I might actually get an app finished this time with decent security.

**Comment by mattchenderson** [comment]
I'm not sure what you're intent is exactly. Is there a problem going the POST version?

If you really want to use the GET method, (as above), you'll need to host a page on your site that matches the /.auth/login/customauth route, and it needs to finish by redirecting to /.auth/login/done with the user object as a URL fragment (so really /.auth/login/done#token=<userobject>).

All told, most custom auth solutions just use the POST. You can gather credentials via native controls instead of a webview, and it ends up being less code on the backend.

**Comment by nhwilly** [comment]
Sorry, that question wasn't very well worded.  

All I did was change the signature, nothing more.  

While debugging the deployed version of the server on Azure I could see the POST was being hit on one signature and, since I didn't have a GET on the controller, I was getting the error that was referenced when I used the other signature.

Perhaps I have this set up wrong, that's why I asked the question.  I don't see how a signature change would switch the call from a POST to a GET.

Here is my startup.cs route configuration
```
config.EnableSystemDiagnosticsTracing();

config.Routes.MapHttpRoute( "CustomAuth" , ".auth/login/CustomAuth" , new { controller = "CustomAuth" } );

new MobileAppConfiguration()
   .UseDefaultConfiguration()
   .ApplyTo(config);

```
I thought I'd stuck to the script in the custom auth section of the docs pretty well, but I make plenty of mistakes, for sure.

**Comment by nhwilly** [comment]
I forgot - thanks for the quick response.

**Comment by nhwilly** [comment]
Actually, don't bother responding to this, I'm beginning to get this figured out.  I think the GET is for a refresh token and I was abusing the signature.

**Comment by andrekiba** [comment]
I'm trying to implement custom auth using the LoginAsync overload of MobileServiceClient. I'have a custom auth controller

```
[MobileAppController]
public class CustomAuthController : ApiController
{
   public async Task<IHttpActionResult> Post([FromBody] JObject assertion)
  {
    ...
  }
}
```

and inside backend startup I set the route

`config.Routes.MapHttpRoute("CustomAuth", ".auth/login/CustomAuth", new { controller = "CustomAuth" });`

On client side the call is:

```
var credentials = new JObject
{
    ["email"] = username,
    ["password"] = password
};            
MobileServiceUser user;
try
{
    user = await MobileService.LoginAsync("CustomAuth", credentials);
}
catch (Exception ex)
{
    Debug.WriteLine(ex.Message);
    throw;
}
```

I think all it's correct but I cannot call the controller with LoginAsync method (in debug I set a breakpoint on first instruction of controller).
And I connot even see the exception because the catch block it's never reached.
But I can send request to CustomAuthController using Postman for example and in this case the debug breakpoint is reached...
I don't understand why!!
I'm trying to debug LoginAsync (that uses MobileServiceTokenAuthentication) decompiled code without success...please help!

**Comment by nhwilly** [comment]
I'm the last person that should be helping anyone in this forum since I don't know much (and I could be totally wrong), but I had a very similar experience.

I believe that this call adapts to what the signature is.  If you are passing a provider token, it performs a GET so that a MobileService token is returned.  You would do this if you used the client side SDK's to get the identity provider's token directly from the provider first, and then passed that token to the MobileService.

If you are passing the provider type then a POST is performed.  You might do this if you are trying to do a server side authentication, allowing the Google (or whatever) login page to be presented in the tiny browser window.

I'm not sure exactly what's happening in your case as I seem to have a mental block on this stuff and I always have to take a full day's run at it before I think I understand any of it.

I know it wasn't much, but maybe that'll get you looking at other approaches.

**Comment by lindydonna** [comment]
@andrekiba I'd recommend posting your question on StackOverflow, so that more people can see it and help out.

**Comment by andrekiba** [comment]
thanks nhwilly but I don't understand. The LoginAsync overload takes the custom (string) provider name (not the built-in type like Google, Twitter...) and a simple JObject that contains username and password filled with custom login page. The authentication is server side (the backend calls auth0 rest api which returns a delegation token, whith this unique token then I call Microsoft.Azure.Mobile.Server.Login.AppServiceLoginHandler which return a JwtSecurityToken that is ok for Azure). I think the POST request is correct beacuse it is the same that is made in Postman...

http://stackoverflow.com/questions/37851855/azure-mobile-apps-custom-authentication

**Comment by nhwilly** [comment]
Sorry, I was just trying to point out that the same method triggered a POST with one signature and a GET with another and that really threw me at first.  I ended up examining the exception to figure out that I wasn't making a POST call.
