### ISSUE TITLE
Reduce number of server calls on a Pull operation

### ISSUE THREAD

**Issue by seanfisher** [Azure/azure-mobile-apps-net-client#162]
(note added by @lindydonna)

The pull operation makes multiple requests to the server since it doesn't know the server pagesize. This could be improved by either having a metadata endpoint that provides the pagesize for each table, or by having the server send something in the response to indicate whether there are more records.

---

Hey everyone,

I'm seeing three requests to the server when I do a PullAsync no matter what I specify as my max page size.

```
_table.PullAsync(queryName, _table.CreateQuery(), new PullOptions { MaxPageSize = entitiesAtATime });
```

No matter what I put as my `entitiesAtATime` I'm seeing at least three HTTP requests from the client. For example, the following table has 1 row in the database on the server:

```
Making GET request to: http://myendpoint.azurewebsites.net/tables/MyTable?$filter=(updatedAt ge datetimeoffset'1970-01-01T00:00:00.0000000%2B00:00')&$orderby=updatedAt&$skip=0&$top=50&__includeDeleted=true
Received response (OK)
Making GET request to: http://myendpoint.azurewebsites.net/tables/MyTable?$filter=(updatedAt ge datetimeoffset'2016-02-12T15:47:46.0170000%2B00:00')&$orderby=updatedAt&$skip=0&$top=50&__includeDeleted=true
Received response (OK)
Making GET request to: http://myendpoint.azurewebsites.net/tables/MyTable?$filter=(updatedAt ge datetimeoffset'2016-02-12T15:47:46.0170000%2B00:00')&$orderby=updatedAt&$skip=1&$top=50&__includeDeleted=true
Received response (OK)
```

If I change MaxPageSize to a larger number I still get the following:

```
Making GET request to: http://myendpoint.azurewebsites.net/tables/MyTable?$filter=(updatedAt ge datetimeoffset'1970-01-01T00:00:00.0000000%2B00:00')&$orderby=updatedAt&$skip=0&$top=10000&__includeDeleted=true
Received response (OK)
Making GET request to: http://myendpoint.azurewebsites.net/tables/MyTable?$filter=(updatedAt ge datetimeoffset'2016-02-12T15:47:46.0170000%2B00:00')&$orderby=updatedAt&$skip=0&$top=10000&__includeDeleted=true
Received response (OK)
Making GET request to: http://myendpoint.azurewebsites.net/tables/MyTable?$filter=(updatedAt ge datetimeoffset'2016-02-12T15:47:46.0170000%2B00:00')&$orderby=updatedAt&$skip=1&$top=10000&__includeDeleted=true
Received response (OK)
```

I know that `MaxPageSize` is working because when I try to sync a table with 3000 rows and page size of 50 it makes a bunch of requests, but once I set it to 10,000 it only makes these same three requests. This happens on both the first time I call `PullAsync()` and subsequent times.

Any ideas?

**Comment by lindydonna** [comment]
You should only see 3 requests on the first sync, after that, you should see 2 requests. This is how offline sync work--there's no sync endpoint, so it queries for changes that are newer than the last sync (the second request). Then, it makes another request and skips the record it already got, until it gets no records.

For more on this, see [How offline synchronization works](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-offline-data-sync/#how-sync-works). 

We're exploring options for creating a sync endpoint, but for now, this is the behavior of the SDK and doesn't appear to be a bug.

**Comment by seanfisher** [comment]
@lindydonna Thanks for the quick response. I read through the link you attached, and I'm still a little confused. On the initial sync, this request:

    Making GET request to: http://myendpoint.azurewebsites.net/tables/MyTable?$filter=(updatedAt ge datetimeoffset'1970-01-01T00:00:00.0000000%2B00:00')&$orderby=updatedAt&$skip=0&$top=10000&__includeDeleted=true

should return one record, the only record in the database. It takes the top 10,000 records since 1970. If the number of records (1) returned is less than the "top" value (10,000), why would the SDK assume that there are more records to be returned if it makes another query? And then why make yet another, third request? The SDK knew from the very first request that there was only one record newer than 1970 in the database. If the first request returned 10000 rows I could see how it would make another request to get the rest of the data, and it will keep doing that until the number of records returned is less than the "top" value.

Now, for my comment that I'm seeing three requests every time we sync, even the second time: I assume this is because we are purging each table every time before syncing, so I'm not as concerned that we are seeing the same behavior for the second time we pull as well as the first.

**Comment by lindydonna** [comment]
The reason is that the SDK doesn't know what the server batch size is, which will always take precedence. On the .NET server SDK, it defaults to 50 records. This is by design, since a rogue client could request way more records than is reasonable, and the server decides whether or not to honor that request.

The only way to solve this would be if the client could query the server's batch size for each table and then use that to determine if it had had a full batch or if it needed to make more requests. That would only save one request though, so a better solution is a sync endpoint.

**Comment by seanfisher** [comment]
OK that makes sense and explains why two requests are needed. What about the third request? And I assume you don't want to return the server's batch size with every request because the endpoints are supposed to be RESTful endpoints of the entities themselves, and not contain any syncing metadata?

Just out of curiosity, what do you mean by a sync endpoint? I'm imagining an endpoint that returns not only the records themselves but this additional syncing metadata (like the batch size). Are you also looking into registering the client with the server so the server keeps track of last synced items and such?

Thanks for your responses, I know I've been asking lots of questions recently. :) We're trying to use Azure Mobile Apps for a large, complex platform and so we're naturally bumping into some of the limitations of the SDK, and I appreciate your and others' help as we work through the kinks. Kudos to the development team for their efforts thus far.

**Comment by lindydonna** [comment]
The third request is because the last updated timestamp was newer relative to the query. The logic works like this:

while (timestamp > prevTimestamp) {
   records = Get records
   prevTimestamp = timestamp;
   timestamp = MaxTimestamp(records);
}

Then it does another round of queries, by skipping the records in the last batch, to handle the case where all records in the batch have the same timestamp. This means that you'll have inefficient pulls if you have reference data all with the same timestamp that don't fit in a batch.

So, if you see a request that starts with the 1970 query, there will be at least 3 requests in the pull, but the newest timestamp will be saved as part of incremental pull using the query key you provided. Then, the next pull should only do 2 requests (assuming no new records), since it there will be one record returned with the max timestamp that was previously saved, then one request that does the skip logic.

**Comment by seanfisher** [comment]
OK, thanks for the explanation. Let me see if I can sum up.

The three-query system, while inefficient, is necessary to ensure accuracy. The "extra" two queries are for the cases where 1) the server's max page size is configured differently than the client's and 2) there are more records with the same timestamp than fit into a page. The solution for improved efficiency, while still maintaining accuracy, is to let some metadata be transferred from the server to the client, possibly including the number of records left to sync for the current sync session and the server's total page size. Transferring this metadata is not currently implemented but is under discussion.

Do you have any insight into the prioritization of this sort of efficiency improvement in the codebase? We're seeing sync times for the entity above to be ~3 seconds even with only one record in the database, and so we're trying to pare down wherever we can, and eliminating the two extra HTTP connections, along with the two extra rounds of processing the server has to do to query the database, would make a big difference, especially when we've got dozens (and growing) of entities to sync.

**Comment by lindydonna** [comment]
The fix we want to do is add a sync endpoint, where the client would get an opaque continuation token on each request, and the server would use it to resume the sync. This would have a lot of improvements, including the potential for implementing stable paging. (Right now, there are bad corner cases if records are being updated in the middle of the sync operation). Other benefits of the sync endpoint is that it would be easier to integrate with other data sources, some of which have efficient queries for getting changes.

Unfortunately, it's a really big change, and we haven't even started the design work. It's unlikely to be completed anytime soon, but we can post some design notes once we start. 

To be clear, you'll see only 2 queries if there are no changes to the table, but I agree that it's extra overhead. We hadn't planned on implementing the page size optimization (by having the server send the page size), but I can bring it up with the team. 

Another approach you might want to consider is to pull changes less frequently. You could have the server send a silent push notification to the client when there are changes for a given table. You can even optimize this so that it is specific to the client query. For instance, if I'm only interested in my own todo items, then the server could send a push notification if a new todo item is added that belongs to me.

**Comment by lindydonna** [comment]
I forgot another option: in additional to/instead of the push notification, you could also make a custom API where you can get the last updated timestamp for each of your tables. Then you know which ones to sync.

**Comment by lindydonna** [comment]
The issue is under consideration, but unlikely to be implemented soon. We do take pull requests, however. I'll update this issue to reflect the ask.

**Comment by Vishwaraddhayya** [comment]
Is this issue still being worked on ?

**Comment by shivprasadd8** [comment]
Is there any way to change timestamp. Because I am purging user related table data. After new user loging I need new user all data not that data which is updated after mobile sdk have max timestamp.

**Comment by gordonsnc** [comment]
I tried the maxpagesize to 1000, however server returns only 50 records each time, the maxpagesize did not reduce the call number at all.

**Comment by TroubleMakerBen** [comment]
Hi @gordonsnc,

I think Lindy answered the question above already:

>The reason is that the SDK doesn't know what the server batch size is, which will always take precedence. On the .NET server SDK, it defaults to 50 records. This is by design, since a rogue client could request way more records than is reasonable, and the server decides whether or not to honor that request.

Other than that, we don't plan to work on changing the existing behavior at this point,
