### ISSUE TITLE
MobileServiceTable.UndeleteAsync does not pass the content to MobileServiceHttpClient

### ISSUE THREAD

**Issue by mrsmitty** [Azure/azure-mobile-apps-net-client#163]
https://github.com/Azure/azure-mobile-apps-net-client/blame/master/src/Microsoft.WindowsAzure.MobileServices/Table/MobileServiceTable.cs#L374

method populates "content" but sends null as the content parameter to MobileServiceHttpClient.RequestAsync

I'm attempting to undelete and update an item, however the server responds HttpStatus 400 (bad request) because the client is not providing a valid body in the POST. Have confirmed the TableController.Undelete(string id, Delta<T> patch) works when using something like Fiddler.

**Comment by lindydonna** [comment]
This is by design--you need to do a separate request to update the item after undeleting it. Part of the reason has to do with the way conflict handling is done for the update vs. undelete case.

**Comment by mrsmitty** [comment]
The ability to Update and Undelete in a single action seems to be supported by EntityDomainManager
https://github.com/Azure/azure-mobile-apps-net-server/blob/master/src/Microsoft.Azure.Mobile.Server.Entity/EntityDomainManager.cs#L135

If this is by design, why does UndeleteAsync bother settings the `content` variable and then doing nothing with it?
https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.WindowsAzure.MobileServices/Table/MobileServiceTable.cs#L369

I'll generally be handling the undelete as a result of a 404 in my IMobileServiceSyncHandler. The current implementation requires updating my local version after the undelete and re-executing the operation. This is additional complexity over sending the content with the POST.

**Comment by lindydonna** [comment]
Ah yes, I forgot that this is an behavior difference between the .NET and Node server SDKs. The Node server SDK ignores the body, and .NET has a more lenient implementation that really should have been consistent. The client SDK has to work with both server SDKs, so we can't change this--otherwise our tests would fail and show a difference in behavior between the 2 servers.

You might be able to work around this by adding a delegating handler and rewriting the outgoing request. You should still update your local copy though, since otherwise you won't get the new value for the Version field.

**Comment by mrsmitty** [comment]
Thanks for the update regarding the reasoning. I have a working solution for this now by retrying the PATCH operation after the UndeleteAsync and updating with the returned "version".
