### ISSUE TITLE
Add support for .NET Standard

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-mobile-apps-net-client#190]
Customer reported [issue](https://social.msdn.microsoft.com/Forums/en-US/c7f419f7-b434-40e8-9dc2-9e26a8cec9c7/azure-mobile-sdk-netstandard?forum=azuremobile&prof=required).

Currently you can't install the Microsoft.Azure.Mobile.Client package to a netstandard project because certain dependencies are incompatible producing the following error:

Microsoft.Azure.Mobile.Client 2.1.0 is not compatible with .NETStandard,Version=v1.3.
Microsoft.Bcl 1.1.10 is not compatible with .NETStandard,Version=v1.3.
Microsoft.Net.Http 2.2.29 is not compatible with .NETStandard,Version=v1.3.
Some packages are not compatible with .NETStandard,Version=v1.3.

Need to add support for [.Net standard](https://docs.microsoft.com/en-us/dotnet/articles/standard/library)

**Comment by ssweriduk** [comment]
Bump. Same issue here. Tried to update to .net standard, but can't seem to get past this frustrating oversight

**Comment by InquisitorJax** [comment]
looking forward to this. 
Usually one can still add a reference to PCL nugets from .NETStandard, but it appears that azure mobile apps contains a conflicting HttpClient reference which cannot be resolved. Therefore cannot upgrade to .NETStandard until this is fixed.

**Comment by aalmada** [comment]
I'm getting this error when using version 3.0.3 on a netstandard1.1 project:

1>CSC : error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\antao\.nuget\packages\Microsoft.Net.Http\2.2.29\lib\portable-net40+sl4+win8+wp71+wpa81\System.Net.Http.dll' and 'C:\Users\antao\.nuget\packages\System.Net.Http\4.3.0\ref\netstandard1.1\System.Net.Http.dll'. Remove one of the duplicate references.

**Comment by adrianhall** [comment]
I have a branch that I'm working on now - if anyone wants to try building it - fork adrianhall/azure-mobile-apps-net-client branch netstandard11 - I'm still testing, but early availability for those that want to take a peek.

**Comment by adrianhall** [comment]
Copying the discussion from the PR:

@twsouthwick One thing to consider since you are planning on having this a major change: Do you want support for the same platforms, or are you okay dropping support for older platforms (such as WinPhone 8.0)?

@adrianhall I think we want to move to .NETStandard 1.2 or 1.3 - I'm ok with dropping support for Windows 8.0 and Windows Phone 8.0 in the v4.0.0 release (which is what this will become)

@twsouthwick Ok. After looking more at the code (and having done multiple conversions to .NET Standard), I'm not sure about the original direction I took with this. The project right now is bundling two libraries with every platform: a platform specific and a portable. Instead of doing this, have you thought about using shared projects and having a single library for each platform, but have it the same name? Or can you get all that you need from .NET Standard and are hoping to eliminate any platform specific code?

@adrianhall It's more of a platform intent. We need to support Xamarin.iOS, Xamarin.Android, Xamarin.Forms (Windows 8.1, Windows Phone 8.1, UWP, iOS, Android), UWP, Windows Phone 8.1 and Windows 8.1.

There are two problematic areas that always come up - the first is identity. We use Xamarin.Auth for the Xamarin components and native web forms for the others. The second is the offline sync cache, which uses SQLitePCLRaw for the offline store.

We need a single library, so the same code can be used in a cross-platform solution (e.g. when we have a Xamarin Forms app that covers UWP, iOS and Android.

**Comment by adrianhall** [comment]
I think @aalmada is running into #82 specifically, so that may also be a predecessor step to going full on .NETStandard.

**Comment by adrianhall** [comment]
Release 4.0.0-alpha - .NETStandard 1.4 release.
