### ISSUE TITLE
DateTime values that were stored as ticks since the Unix Epoch cannot be retrieved by another library

### ISSUE THREAD

**Issue by zjlanglois** [Azure/azure-mobile-apps-net-client#195]
We are dealing with a cross-library exception on our project. Short and sweet: we use AzureMobileServices to handle most of our data in our offline application. However, on occasion, we want to query the SQLite database directly with SQLite.Net-PCL.

AzureMobileServices stores dates as ticks since the Unix Epoch, so ticks since 1970-01-01. Whenever a date is stored as 1969-12-31 or below, and the data is synced down, there is an exception thrown by SQLite.Net-PCL as it cannot interpret negative dates...

Is there a way we could override how dates are stored and retrieved for Azure Mobile Apps Net Client?

**Comment by lindydonna** [comment]
If you want use a different SQLite library, the only supported way is to create a custom local store implementation by creating an implementation of IMobileServiceLocalStore. Have you done that, or are you accessing the database with the other library?

**Comment by zjlanglois** [comment]
That's interesting, is there an example somewhere that we could take a look at? At the moment we don't do that. Alternatively is there a way we could query the database directly with custom SQL using the IMobileServicesSyncTable?

The only reason that we need to query the database directly is because we can't access the table by doing a Table.Where(record => MyIds.contains(record); similar to issue #172.

**Comment by lindydonna** [comment]
@zjlanglois You would use the implementation of MobileServiceSQLiteStore as a starting point, and use a different library for querying.

It's a current limitation of the SQLiteStore that it doesn't expose the read query operation, which I've created a new issue for: #196. You can work around this for now by creating your own subclass that exposes the protected member. However, you will need to add your own lock in order to ensure that the read does not interfere with any concurrent writes that are caused by SDK operations. See https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.WindowsAzure.MobileServices.SQLiteStore/MobileServiceSQLiteStore.cs#L100. 

If #196 covers your scenario, then please close this issue and add any necessary comments on that one. Thanks!

**Comment by zjlanglois** [comment]
It should at least alleviate the issue that we are having.
