### ISSUE TITLE
Event StoreOperationCompletedEvent is fired even if the table was not updated

### ISSUE THREAD

**Issue by kinex** [Azure/azure-mobile-apps-net-client#269]
Based on my tests PullAsync seems to always pull the last row of a table even if there are not any table updates done (subscribed event "StoreOperationCompletedEvent" reports that a row was updated). If there are several rows in a table, only the last row is reported as "updated". This same issue happens with all tables in my database. I am worried about this issue because I guess it causes me unnecessary (Azure) costs and also triggers unnecessary UI refresh events in my app. 

I am using release 3.0.3.

**Comment by Hangarspace** [comment]
I've been experiencing the same issue recently albeit with an older 2.1.1 version.. I thought we had 'got around' the problem by adjusting the delta token in the __config table which is used to track the updates by adding 1 millisecond to it. But after looking at the source, this value is actually cached internally so any adjustments made to the delta tokens are not reflected until the the app is restarted. (I'm sure this was working in versions pre-2.0.0)

The generated sync query includes a 'ge' (greater-than-or-equal-to) filter on the timestamp and it might sound like replacing this with a 'g' (greater-than) filter instead would be a better option but there is also a difference in the resolution of the timestamp value used between SQLite and SQLServer so that change wouldn't help in itself. Disabling the caching wouldn't solve it either for the same reason, but would at least allow any external adjustments to the delta tokens to be reflected in the sync query.

When this issue has been discussed before, it's been mentioned that the current behavior is 'by-design' and unlikely to be changed until a complete redesign of the sync endpoint methodology. 

As a workaround that doesn't involve rolling your own version of the azure client libraries with any caching code changes, you could update the delta tokens by 1 millisecond following each sync and then create a web api method that you call before each pull to check if there are any updates pending.

**Comment by kinex** [comment]
Difficult to understand how this could be related to any "design". Sounds more like a simple bug in an if statement. Anyway, if this is caused by design issue, the design should be fixed. In my opinion this (pulling MODIFIED rows) is one of the core features of this whole SDK and it does not work properly. Reporting rows updated and pulling them when they were not updated does not make any sense and it causes unnecessary network traffic and costs.

Anyway, I am just integrating this SDK into my app so I guess I have to implement some (hopefully) temporary workaround. Thanks for the ideas!

**Comment by shrishrirang** [comment]
The incremental sync algorithm works by checking what records changed since the previous pull. It is important to start from the timestamp of the last fetched record to be sure you don't miss updates that happened immediately after your previous pull, i.e. changes that happened immediately after the previous pull but have the same timestamp in the database. Using greater-than as mentioned in an earlier comment has a tiny chance of missing such records and that is the precise reason for resuming where we left off (>= timestamp of last fetched record).

Some of the work on our backlog could likely involve a design change to how we perform incremental sync and that could change whether we page by timestamps. This is the larger change @Hangarspace mentioned.

**Comment by kinex** [comment]
Good to know that. But why did you close the bug without fixing it first? This issue needs visibility and should be tracked as all other bugs. Some developers won't probably even realize they have this issue (unless they listen to StoreOperationCompletedEvent) and they pay unnecessary Azure costs if they don't implement any workaround.

**Comment by adrianhall** [comment]
I have yet to see an argument, especially around "cost", against the current design that has actually held up.  The current design ensures we are always correct (as opposed to mostly correct).  There is no additional Azure costs (the Azure App Service cost does not include an API cost - only memory usage, and SQL Azure would be hit irrespective to determine the last record updated).

**Comment by Hangarspace** [comment]
It becomes an issue when hundreds or thousands of rows can be updated on the sql server very quickly. Then every time the app does a sync it pulls all this data for no reason. 

In a business case whereby a days data for a mobile user is prepared overnight but they are required to regularly check for updates during the day then it can add up.

Whilst azure may not charge, mobile service operators certainly do.

**Comment by kinex** [comment]
This can be seen also as two separate bugs:
1. Unnecessary data transfer causing at least data transfer costs.
2. Event `StoreOperationCompletedEvent` is fired even if the table was not updated. The event data tells also the `RecordId` that was "updated", but actually it was not updated. Or now we don't know was it really updated or not. I am not listening this event just for fun, I need to trigger important actions when a record in a given table is updated (and only in that case). For example updating UI and updating all (calendar) alarms my app has set.

In my app there are over 10 tables, so pulling all of them in each sync causes quite a lot of unnecessary data transfer and other extra actions like resetting all alarms several times.

**Comment by kinex** [comment]
One consequence of the issue 2. "Event  StoreOperationCompletedEvent  is fired even if the table was not updated" is that your other library "Azure/azure-mobile-apps-net-files-client" which relies on this event downloads unnecessarily all files attached to the last records of all tables on every sync. This will easily result downloading megabytes of data unnecessarily over and over again.

**Comment by adrianhall** [comment]
Understood - I'll take a look at the StoreOperationCompletedEvent update - that should be an easy fix.  We are looking at improvements to the sync protocol which will alleviate the unnecessary data transfer.  I'll post once we have something to talk about.

**Comment by elamalani** [comment]
@gc435 Thanks for using Azure Mobile Apps. Since this issue is almost 2 years old, I'll close it for now but feel free to ask us questions if you have any. Also, please refer to the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps).
