### ISSUE TITLE
Nuget Package Installation fails for PCL

### ISSUE THREAD

**Issue by CodePhobie** [Azure/azure-mobile-apps-net-client#337]
The nuget package installation for iOS, Android and UWP projects work in Visual Studio 2017. 
The installation for the PCL project(s) fail with:

```
Install-Package : Could not install package 'Microsoft.Azure.Mobile.Client 4.0.0'. You are trying to install this package into a project that targets 
'.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. 
For more information, contact the package author.

```

Anything I can do?

Thanks for this new version, was waiting some weeks to be able to reuse the google-authentication again :)

**Comment by dhei** [comment]
Hi @CodePhobie, as part of the v4.0.0 release, we moved to .NET Standard 1.4. As a consequence, we no longer support Xamarin.Forms using portable class libraries, please use .NET Standard libraries or shared projects instead. We only support Xamarin.Forms using .NET Standard libraries or shared projects.

We are in the process of updating our documentation. 

Hope this helps. Thanks.

**Comment by brminnick** [comment]
@dhei I love .NET Standard support, but is it possible to provide backward-compatibility for PCLs?

Most libraries still don't support .NET Standard, which means many developers are forced to remain on v3.1.0.

**Comment by MatkovIvan** [comment]
@brminnick to include PCL libraries to your .NET Standard project you should add this(`imports`) to your `project.json`:
```
"frameworks": {
  "netstandard1.4": {
    "imports": "portable-win8+net45+wpa81"
  }
}
```

**Comment by mnmilner** [comment]
Could we get a version 3.2.0 that supports the new login features but still targets PCL? Given that Xamarin.Forms does not yet support .NET Standard (I know, preview) and VS 2017 does not have a solution template for creating a new Xamarin project with a .NET standard library, it seems like removing PCL support completely is a little premature. I agree that a major version number should be used for the .NET standard support, but Xamarin hasn't caught up yet and those creating projects would like to use PCL and still get the updated support for the server login flow.

**Comment by MatkovIvan** [comment]
@mnmilner Xamarin.Forms for PCL works well with .NET Standard projects (see my post above).  But you are right about template for creating.

**Comment by mjsmith26** [comment]
I am experiencing this issue as well. It would be great if we could get some backward compatibility.

**Comment by craigathon** [comment]
@dhei The frustration around this for me is that issue #264 is making our apps unusable. We aren't ready to move to .NET Standard 1.4, we need to deliver the quick fix.

**Comment by fileman** [comment]
You can use PCL library inside Net Standard, but **Dont use "change target framework" in VS**
You need to create new library project and migrate manually for VS2017 project follow [this](https://xamarinhelp.com/visual-studio-2017-net-standard-xamarin/)

**Comment by MatkovIvan** [comment]
[Sample with Xamarin.Forms (PCL) and Azure Mobile Client SDK 4.0.0](https://github.com/dhei/azure-mobile-apps-xamarinforms-login-sample)

**Comment by mnmilner** [comment]
I get that we CAN make this work, but we are hacking on project.json to get it done. Easy enough to manage for a developer, so that's not the issue for me. First, project.json is deprecated, so I'm not a fan of relying on that file. Second, I feel like there are valuable fixes in this release that folks would like to pick up by simply updating their NuGet package install. If they have an app built on PCL, which they probably do if they aren't creating a new one, then they can't update for the fixes without taking the time to test out .Net Standard as their library format. It might not introduce any issues, but conscientious developers will have to test that out to ensure nothing breaks. 

All that said, if it's a done deal, that's fine. But honestly this transition period from PCL -> .NET Standard and the mess of project.json is going to be a strain until VS, NuGet (and all the packages) get caught up.

**Comment by brminnick** [comment]
If you're using a `csproj` instead of `project.json` for your .Net Standard library, you can update the property group to allow it to install NuGet packages that are made for PCLs

```
    <PropertyGroup>
        <TargetFramework>netstandard1.4</TargetFramework>
        <PackageTargetFallback>portable-win+net45+wp8+win81+wpa8</PackageTargetFallback>
    </PropertyGroup>
```

Oren Novotny did a good write-up here:
https://oren.codes/2017/04/23/using-xamarin-forms-with-net-standard-vs-2017-edition/

**Comment by jangaehler** [comment]
Unbelievable, the fucking Azure Quickstart sample app is STILL an PCL Project. How long did you know that you move to .NET Standard 1.4?

**Comment by Quico20** [comment]
I was following a Zumobook from adrian hall to use azure mobile apps, but when I updated to v4.0.0 everything went to directly to garbage, I had to remain on v3.1.0 and i'm new on Azure Mobile Apps, you should changed thing so drastically without publishing somekind of documentation.

**Comment by Rhywden** [comment]
@dhei So, any updates on the documentation and particularly the Quickstart samples?

Because pulling this stunt is REALLY not funny when there are no proper tools yet to switch to the configuration you want and 90% of the stuff listed here as a workaround either does not work or is so error-prone that you shouldn't attempt it.

**Comment by BongaDev** [comment]
@KhanyiTheGreat

**Comment by elamalani** [comment]
@CodePhobie We released the latest version of Zumo .NET client SDK v4.0.2 today where we support PCL based Xamarin.Forms project, please find more information [here](https://github.com/Azure/azure-mobile-apps-net-client/releases/tag/4.0.2).
