### ISSUE TITLE
How-to: Enable Softdelete with Offline Sync Tables

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#355]
Hi,

I have a question if the soft delete is setup properly. I set that in the TableController:

`DomainManager = new EntityDomainManager<TruckAuftrag>(context, Request, enableSoftDelete: true);`

In the Xamarin.Forms App:

```
string TruckAuftragQueryAll = "allTruckAuftragItems";
_truckAuftragTableQuery = TruckAuftragTable.CreateQuery().IncludeTotalCount();

await OfflineSyncStoreManager.Instance.TruckAuftragTable.PullAsync(TruckAuftragQueryAll, _truckAuftragTableQuery);
```

Well all works well. When the `Deleted `table field is set to 1 that record is not transferred to the App. Ok, that's intented.

But I see that the` __includeDeleted=true` is automatically appended in the sent REST API call.

`https://trucker-rolsped-dev.azurewebsites.net/tables/TruckAuftrag?$filter=(updatedAt ge datetimeoffset'1970-01-01T00:00:00.0000000%2B00:00')&$orderby=updatedAt&$skip=0&$top=50&__includeDeleted=true`

**Question**:

What would I have to do if I want to get the deleted records from the TableController deliberatelly? Remove the `enableSoftDelete: true` from the `EntityDomainManager `constructor's argument again or can I set that up in the Table Query?

Thanks for clarification.

best

Eric

**Comment by jwallra** [comment]
I'm a bit unsure what you are confused about.

You're claiming that the `__includeDeleted` field is being added automatically to your API calls?  I assume you're not adding the field automatically when you use `GetTable` or similar.  The expected behavior is that if soft delete is enabled, records will never be removed from the table, but their "deleted" column will be set to true.  The table can also be modified manually from the Azure Portal.

If the field is being added without having been specified somewhere in your code, could you give more context?  It may be a bug, but in the meantime, I'll close this issue.  Feel free to reopen with more context.

Here are some helpful links documenting Offline Sync:
[Zumo Book - Offline Sync Details](https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter3/dataconcepts/#the-deleted-field)
[Using the Client SDKs](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library) (May need to switch to your platform of choice)

**Comment by elamalani** [comment]
@ericbrunner We haven't heard back from you. I am closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!

**Comment by ericbrunner** [comment]
To clarify:

1. It is confusing that __includeDeleted=true  is included in the query params when a PullAsync call on an Offline Table is sent to the TableController 
2. __includeDeleted=true Means: Send me all records including the deleted ones (where Deleted table column set to 1)
3. It does absolutely make no sense in an Offline Table. And I noticed that the deleted one don't get transferred. I guess that __includeDeleted=true is ignored on the EntityDomaonManager for Offline tables or something else goe on.
4. My question was how can I deliberately transfer deleted records from an Offline sync enabled table.
5. Since it is over 6 month ago that I filed that issue, I transfer my deleted records with an Online table using the IncludeDeleted() client API call.
