### ISSUE TITLE
No way to close db connection to be able to delete db.

### ISSUE THREAD

**Issue by Falven** [Azure/azure-mobile-apps-net-client#379]
We have a case where we have to close the DB connection so we can delete the DB and re-create it.
This is currently not possible.

**Comment by mrsmitty** [comment]
if you dispose your MobileServiceClient, it also disposes the MobileServiceSyncContext which in turn disposes the sqlite3 connection.

So perhaps try disposing the client, delete the DB, then re-instantiate the client?

**Comment by Falven** [comment]
@mrsmitty I tried this, but for some reason I still get an exception when deleting the db file. I think it would be best to add a function that calls [sqlite3_close_v2](https://sqlite.org/c3ref/close.html) to the MobileServiceClient SyncContext.

**Comment by elamalani** [comment]
@Falven Thanks for using Azure Mobile Apps. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). Since this is a feature request in the product, I'll close this issue for now as we are not adding new features, but feel free to ask us questions if you have any. Thanks!
