### ISSUE TITLE
Failed certification

### ISSUE THREAD

**Issue by ozzy1873** [Azure/azure-mobile-apps-net-client#390]
Microsoft.Azure.Mobile.Client 4.0.2 has a dependency on PCLCrypto, which fails certification. The local cert kit check passes. The following methods appear in the "portable" version of the library even though the Windows Store disallows them:

![error1](https://user-images.githubusercontent.com/8699636/31774787-f2be5f3a-b4a3-11e7-9bca-39d43c5dbe61.png)

**Comment by MatkovIvan** [comment]
Hi @ozzy1873,

Thanks for getting in touch.
`PCLCrypto` used only in assemblies for Android, iOS and PCL platforms. In `4.0.2` we reintroduced PCL library only for compatibility reasons. Since version `4.0.0` we support `.NETStandard` which comes as the replacement of PCL, and I recommend using it for shared code. `.NETStandard` library doesn't depend on `PCLCrypto` and migration to it should help with this issue.

Best,
Ivan

**Comment by elamalani** [comment]
@ozzy1873 We haven't heard back from you. I am closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!
