### ISSUE TITLE
While using Offline data sync with Azure Mobile Apps SDK Can I control the order in which the table are synced?

### ISSUE THREAD

**Issue by rohithlogiticks** [Azure/azure-mobile-apps-net-client#393]
We are generating the Primary Keys from(GUID) from client side and passing to server.
From some of the articles and blogs we came to know that Azure client sdk pushes the records in random order.
We have created a 2 tables with relations and tested this in offline mode and it works well. So we would like to confirm if the latest client side sdk has done some code fix to send the records in some order.
I wonder why can't they create a queue so that it will push the first in first out manner.

Since we have foreign key relations in server side we need to push the inserts in an orderly manner, is there any mechanism to make this pushes to server in a specified order?

**Comment by vhnatss** [comment]
Yes - you can. You can do with IMobileServiceSyncTable - method

`        Task PullAsync(string queryId, string query, IDictionary<string, string> parameters, bool pushOtherTables, CancellationToken cancellationToken, PullOptions pullOptions);`

pushOtherTables - parameter - if set to false - will push/pull only current table - so you can have pushes ordered. Please remember that Pull always does Push. I believe you can't do Push alone since it's per Sync Context  -pushes everything. Also pls note that records will be pushed in order they were created.

**Comment by elamalani** [comment]
@rohithlogiticks Were you able to fix this issue by using PullAsync() API with pushOtherTables parameter? Please let me know so that we can close this issue. Thanks!

**Comment by logiticks-github** [comment]
We managed to find some other workarounds. The statement 'Also pls note that records will be pushed in order they were created.'  helped in finding the workarounds. So yes you can consider this issue closed. 
Thanks

**Comment by elamalani** [comment]
@logiticks-github Thanks for the update. We will close this issue.
