### ISSUE TITLE
Question: PullAsync incremental using Expression<Func<T, bool>> 

### ISSUE THREAD

**Issue by StargazerNC** [Azure/azure-mobile-apps-net-client#407]
Hi there.
I have an issue with the incremental sync. It may end up being that my understanding of this is not the best, but maybe it's just the implementation that is not that user friendly. So my issue...

I have a table which data depends on User and Client. I need to be able to only pull data for one user and one client at any given time.

When I issue the pull with x => x.Active && x.ClientId (for example) it only woks first time. After that point no matter what ClientId is supplied I get no records. The reason? The query name/id. My query name is the table name plus the user id.

For this to work I had to append also the clientid to the query name so I have a unique query. Now, how to handle this if I have filter based on more conditions? I can see this spiraling to a mess very quickly...

Anyone can clarify if I'm seeing this correctly or not?

Thanks!

**Comment by MatkovIvan** [comment]
Hi @StargazerNC,

Thanks for getting in touch.
Incremental sync is a feature which allows you retrieve only new records based on `updatedAt` value.
The query name is used only on the client and must be unique for each logical query. Otherwise, different pull operations could overwrite the same incremental sync timestamp.
If you want to opt out of incremental sync, pass `null` as the query name. In this case, all records are retrieved on every call.

You can check out our doc to get more details: [How offline synchronization works](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-offline-data-sync#how-sync-works)

Best,
Ivan

**Comment by elamalani** [comment]
@StargazerNC Closing the issue as you can check out the link to see how offline sync works in Azure Mobile Apps. Please feel free to open an issue if you have more questions.
