### ISSUE TITLE
Queue PushAsynk

### ISSUE THREAD

**Issue by CarmineScala92** [Azure/azure-mobile-apps-net-client#431]
Hi,
is it possible to know what are the elements in the queue in the pushasynk ?. If the push from error, I would like to see the list of items in the queue and figure out what the problem is.

Is there a way to access the list of items in the queue?

Thank you so much for the support.
Carmine

**Comment by ltaljaard** [comment]
I haven't looked at this for a while but I believe there is a table on the client side that stores the queue that you can view using a 3rd party sqlite tool on the device. Otherwise there is a method ExecuteTableOperationAsync that you can override in IMobileServiceSyncHandler (implement your own Synchandler class which implements IMobileServiceSyncHandler and use that class as you sync handler throughout your client side app). It gets called for each operation that is buffered on the client side so from there you'll be able to see the items in the queue. (But normally one's problems are not sue to an internal error with the queue, that part of this solution works ok actually).

**Comment by bmourat** [comment]
Closing this one, if you'll have any more questions please feel free to reopen.
