### ISSUE TITLE
How can I use this in my C++ UWP project?

### ISSUE THREAD

**Issue by mjfusa** [Azure/azure-mobile-apps-net-client#505]
Can't use azure-mobile-apps-net-client in a UWP C++ project.
I'm getting the following error when importing the NuGet package:

> Install-Package : Could not install package 'Microsoft.Azure.Mobile.Client 4.1.1'. You are trying to install this package into a project that targets 
> 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact 
> the package author.
> 

Does this package support C++?  I understand NuGet has a limitation with not supporting C++  packages. Any guidance on getting this to work with our C++ project would be appreciated. 

Thanks,
mjfusa

**Comment by Jamminroot** [comment]
Hey, @mjfusa, im sorry for a delayed response.

Unfortimately, we don't support UWP C++ directly since it is C#, but as an option you can create a wrapper for managed code (.NET assembly) - you basically create other project C++ project which would support managed code, and reference it from your project.
There's a [block](https://docs.microsoft.com/en-us/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp?view=vs-2019) in MS Docs dedicated to Interoperability
You can also check this [sample](https://code.msdn.microsoft.com/CppCLINETAssemblyWrapper-5485fae2)
