### ISSUE TITLE
Declining application authorization during facebook login puts client into bad state

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-mobile-apps-net-client#52]
See https://github.com/Azure/azure-mobile-services/issues/738 for full description. 

This issue was reported for WP8.1 but we should test on multiple managed platforms.

**Comment by paulbatum** [comment]
Hey @aziel can you take a look at this when you get back?

**Comment by aziel** [comment]
Shrirang is looking at this from MobileApp perspective.  Different issue occurring where the login/facebook/callback endpoint result is displayed by browser, which must then be exited.

In MobileService the WAB session needs to be cancelled as in the customer snippet.

**Comment by shrishrirang** [comment]
In Mobile Apps, declining permission as mentioned in issue https://github.com/Azure/azure-mobile-services/issues/738 causes no problem on Windows Phone 8.1 and Win Desktop. Looks like in Mobile Services for some reason declining permission returns with `result.ResponseStatus == WebAuthenticationStatus.Success` which is the root cause of the bug.

We should try running this scenario on different Xamarin platforms to see that declining permissions does not take us to a 'dead end' page from where there is no way to get out. A similar issue existed in Cordova that caused you to land on a dead end page and hitting back took you to the previous page in history.

**Comment by aziel** [comment]
Need to test Xamarin clients as per Shrirang's comment.
