### ISSUE TITLE
PullAsync incorrectly wraps 401 error as 404

### ISSUE THREAD

**Issue by aziel** [Azure/azure-mobile-apps-net-client#65]
Repro steps:
Set up a backend and client app with Offline features.
Set up AAD auth.
Put [Authorize] attribute on TodoItem table controller.

Run the backend in local-debug (i.e. locally hosted backend)

In client:
Set MobileService.AlternateLoginHost to point to the web app.
Execute LoginAsync to get a token.  Execute PullAsync against the table.

Catch the MobileServiceInvalidOperationException, notice that it is 404.

Execute the same request against the table in Fiddler.  Notice that it is 401.

Seems like PullAsync is wrapping the 401 received from backend as a 404.

**Comment by lindydonna** [comment]
@aziel Does this only happen when you're running locally?

**Comment by elamalani** [comment]
@aziel Thanks for using Azure Mobile Apps. Looks like this issue is almost 2 years old. Were you able to resolve it?

Since its an old issue, I'll close it for now but feel free to ask us questions. Also, please refer to the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps).
