### ISSUE TITLE
If service returns HTML, get MobileServicePushFailedException with status Complete and no error

### ISSUE THREAD

**Issue by PaulARoy** [Azure/azure-mobile-apps-net-client#70]
Updated by @lindydonna

If the server returns an HTML page for some reason (server misconfiguration, transient gateway error), the SDK tries to deserialize the HTML and fails. Then, it returns a MobileServicePushFailedException with no errors. The SDK should treat this case as if it were a 500.

---

Hi there,

First of all thanks for this amazing library!

I am using SQLiteStore and the managed version of the framework on a PCL project (then used by Xamarin on Android, iOS and WP).

Often I experience a `MobileServicePushFailedException` having the status « Complete » and absolutely no error (`exception.PushResult.Errors`) during the synchronization.

I have trouble understanding why and knowing if there is anything I can do about it.

Has anyone ever seen this? Could it be a bug?

Note: I do not know if it could impact the result but for full transparency I am using a workaround for 409 errors as seen [here](https://social.msdn.microsoft.com/Forums/azure/en-US/e595ecce-417d-4cc0-b68b-f15cf692f555/the-operation-failed-due-to-a-conflict-violation-of-primary-key).

**Comment by adrianhall** [comment]
Hi Paul,

Could you possibly share your code that you are using?

**Comment by mrsmitty** [comment]
I've just experienced a bug similar to this with xamarin. We have a large amount of data being sent with the verbs PATCH and PUT ~70KB. The mono system.net.http library handled sending the request but failed half the time reading the response and would eventually cause HttpClient to timeout.

This only occurred when we were expecting a 412, precondition failed. In this scenario, the response content would have been similar in size to the request and it seems this is where HttpWebResponse has the issues.

We were advised to try the Xamarin Alpha channel for updates to get the latest mono libraries. This resolved our issue. It might be worth investigating this for your scenario depending what version of mono you're on.

**Comment by PaulARoy** [comment]
Sorry for the late answer.

I am afraid you are going to be a bit more specific, the project itself cannot be shared. What would you wish to have?

I will try with Xamarin Alpha versions if this fixes the problem that would be awesome.

**Comment by lindydonna** [comment]
Closing since it sounds like a Mono issue. Please comment if you have more questions.

**Comment by seanfisher** [comment]
We had this issue where our server was returning a 500 error in the form of an HTML yellow screen of death. Azure Mobile Services saved this HTML page into the __errors table and when it tried to deserialize it as if it were JSON it threw a serialization exception (since '<', the first character in the HTML page, was not valid JSON), which was then wrapped in a MobileServicePushFailedException like the one you describe. The end result was a confusing MobileServicePushFailedException that was marked as complete with no push result errors.

**Comment by lindydonna** [comment]
@seanfisher Interesting--we'll try to repro. Are you using MVC controllers in your server, and is that why it returned HTML rather than a JSON response?

**Comment by seanfisher** [comment]
We're using controllers inherited from TableController<TDto>, and they do typically return JSON error messages. I can't remember why in this instance we got an HTML response, if it happens again I'll post more details.

Thanks for the workaround suggestion - that's a great idea, especially since we have a custom delegating handler that does custom auth and logging for us anyway. What is the expected JSON error format?

**Comment by lindydonna** [comment]
For a 500 error, any additional fields would typically just be used by logging code, so there's no need to customize.

Based on my research, you can get an HTML page if your site is misconfigured, such as missing an assembly or a typo in web.config.

**Comment by seanfisher** [comment]
@lindydonna I figured out one time when it happened. We're hosting our API on Azure, which has a load balancer and some backing instances. When the instances go out for any reason, be it an Azure outage, an app that eats up too much memory and crashes the instance, etc, the load balancer returns a 502 gateway error (in HTML). Since this could be out of the developer's control, what do you think about having the Azure Mobile Apps client handle this issue gracefully by checking the response before inserting the data into the `__errors` table?

**Comment by lindydonna** [comment]
@seanfisher Agreed--I'll file a bug for this. Just out of curiosity, what Azure service are you using to host?

**Comment by seanfisher** [comment]
@lindydonna We're using Azure App Services, with our main API using the Mobile flavor.

**Comment by lindydonna** [comment]
@seanfisher Good choice--that's the service our team runs. :)  I hadn't seen the 502 error before, but I don't have any big workloads running.

**Comment by zezioen** [comment]
Could you confirm that the operation being performed is allowed on the table it's being performed on? I just experienced this same issue and it was because I was trying to update an entry which had it's update permission set to disabled on the server (there wasn't a clear error message but this very vague message)

**Comment by lindydonna** [comment]
@zezioen What error code do you get back for this case?

**Comment by zezioen** [comment]
None, just this vague error message as described above, it did not throw a 403 permission denied error

**Comment by lindydonna** [comment]
@zezioen Right, but what was the actual HTTP error?  I.e., if you do a request in Postman or look at the traffic in Fiddler, what is the response code?

**Comment by zezioen** [comment]
In Postman it returned a proper 405 Method not allowed with the content "Method update is not allowed", The Azure library in Xamarin.Forms doesn't relay this error properly it seems

**Comment by lassana** [comment]
@lindydonna 

>it sounds like a Mono issue

I think it is an issue with default HttpClientHandler from mono/Xamarin.Android. AndroidClientHandler works fine on Android 5+ devices, but not on Android 4.4 and lower.

Using ModernHttpClient is a workaround for me.

**Comment by elamalani** [comment]
@PaulARoy Thanks for using Azure Mobile Apps. This issue was opened more than a year back. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). 

I'll close this issue for now, but feel free to ask us questions if you have any. Thanks!
