### ISSUE TITLE
Updating rows while a push is in progress messes up the table

### ISSUE THREAD

**Issue by shrishrirang** [Azure/azure-mobile-apps-net-client#75]
- The table state cannot be recovered back.
- Try running a series of writes (insert, delete, update) to rows in a dirty table while a sync over a slow network is in progress. Check if this works fine. Try doing this a few times as the repro may not be consistent.
- Simulating a slow network can be helpful in getting a consistent repro.
- This issue can be related to one or more bugs mentioned in https://github.com/Azure/azure-mobile-services/issues/615

**Comment by elamalani** [comment]
Hi there, please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). Looks like this issue was opened over 2 years back, I'm closing this for now but feel free to reach out in case you have any questions.
