### ISSUE TITLE
Need webview page customisation [Xamarin.Auth]

### ISSUE THREAD

**Issue by remiroyc** [Azure/azure-mobile-apps-net-client#79]
I implemented facebook authentication on my xamarin forms app with azure mobile app client. I used LoginAsync function. It opens a webview page on android device. But I have few problems
Can I customize (or hide) the header of facebook connection webview? Can I add a loading icon? http://image.noelshack.com/fichiers/2016/07/1455899042-screenshot-2016-02-19-17-17-17.png

It is a pretty ugly screen for my mobile app.

If a have a connection problem, android webview displays this :
http://image.noelshack.com/fichiers/2016/07/1455899042-screenshot-2016-02-19-17-16-55.png

Apparenlty, azure mobile app uses WebRedirectAuthenticator (Xamarin.Auth) so I opened a issue on their account : https://github.com/xamarin/Xamarin.Auth/issues/106

Thanks for your work and your replies.

Best regards. :+1: 

@ggailey777

**Comment by elamalani** [comment]
Hi there, please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). Looks like this issue was opened over 2 years back, I'm closing this for now but feel free to reach out in case you have any questions. Thanks!
